version: '3.7'

services:
    node:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        env_file:
            - .env
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - node
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./nginx/certificates/:/etc/nginx/ssl/